#!/usr/bin/expect -f

set port 59412

spawn ./rerun --retries-on-failure 99999 --metrics-host 127.0.0.1 --metrics-port "$port" tests/exit_with_code.sh

# Run exit_with_code.sh 10 times to set up success counter
set repeats 0
while {$repeats < 10} {
    send "0\r"
    incr repeats
}

# Run exit_with_code.sh with exit code 1 to set up failures counter
set failures 0
while {$failures < 5} {
    send "1\r"
    incr failures
}

# Wait for synchronization.
exec /bin/sleep 0.1

set result [exec curl -i -s "http://127.0.0.1:${port}/metrics"]

if {[string match "* 200 OK*" $result]} {
    puts "✅ HTTP 200"
} else {
    puts "❌ HTTP code is not 200"
    exit 1
}

if {[string match "*success_total 10*" $result]} {
    puts "✅ success_total metric is correct"
} else {
    puts "❌ success_total metric is incorrect:\n$result"
    exit 1
}

if {[string match "*failures_total 5*" $result]} {
    puts "✅ failures_total metric is correct"
} else {
    puts "❌ failures_total metric is incorrect:\n$result"
    exit 1
}
