#!/usr/bin/expect -f

spawn ./rerun --repeat 3 tests/exit_with_code.sh

set prompts 0

while {$prompts < 3} {
    expect {
        "exit with code:" {
            send "0\r"
            incr prompts
        }
        eof {
            puts "❌ less than 3 repeats"
            exit 1
        }
    }
}

expect {
    "exit with code:" {
        puts "❌ more than 3 repeats"
        send "0\r"
        exit 1
    }
    eof {
        puts "✅ expected number of repeats"
    }
}

set status [lindex [wait] 3]
if {$status == 0} {
    puts "✅ return code == 0"
} else {
    puts "❌ return code != 0 (was $status)"
    exit 1
}
