name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🛠 Install dependencies (if needed)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libmicrohttpd-dev

    - name: 👷 Build executable
      run: make build

    - name: 📦 Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: rerun
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
